class_name SurfaceQuery
extends RefCounted
## "What am I standing on?" — the one place movement code asks, so the answer
## cannot drift between the client that predicts it and the server that trusts it.
##
## TWO SOURCES, checked in this order:
##
##   1. VOLUMES — world-space rects registered at runtime by whatever owns a
##      temporary surface. The Ossuran arena registers an ice volume when the
##      forge freezes and drops it when the encounter resets.
##   2. TILE DATA — a `surface_type` custom data layer on the floor tileset, for
##      surfaces that are a permanent property of the map.
##
## Volumes come first because a temporary surface has to be able to OVERRIDE the
## authored one: the arena floor is authored stone and becomes ice for one phase
## without a single tile changing.
##
## The volume path is also the only one that works here today. Nothing in this
## project's tilesets declares a custom data layer, and the forge floor tileset is
## generated by `build_biome_tilesets.gd` — adding a layer to it by hand would be
## erased the next time that tool runs. The tile-data path is implemented anyway
## because it is the correct general mechanism, and a map that DOES declare the
## layer gets it for free.

## Surfaces the movement code knows about. Anything unregistered is DEFAULT, and
## DEFAULT must always behave exactly as movement did before this file existed.
const DEFAULT: StringName = &"stone"
const ICE: StringName = &"ice"

## Name of the optional custom data layer read from TileData.
const TILE_DATA_KEY: StringName = &"surface_type"

## Registered volumes: id -> { rect: Rect2, surface: StringName }.
##
## Static because both the client's movement prediction and the server's own
## simulation need the same answer, and they are different objects in different
## scenes. Keyed by id so a registrant can replace or drop its own volume without
## knowing about anyone else's — an arena that reset by clearing the whole table
## would silently delete a second encounter's ice on a shared world server.
static var _volumes: Dictionary = {}


## Register (or replace) a surface volume. [param id] is the owner's key.
##
## [param map] SCOPES the volume to one map, and passing it matters: the rect is
## in world coordinates, and every map in this project starts near the origin, so
## an arena rect of (32, 32, 704, 480) covers the same coordinates in the forge,
## the woodland and every other map. Without a scope, ice registered in Ossuran
## would make a patch of the overworld slippery for anyone standing in the wrong
## place. Null means "applies anywhere", which only a genuinely global effect
## should ever use.
static func register_volume(
	id: StringName, rect: Rect2, surface: StringName, map: Node = null
) -> void:
	_volumes[id] = {
		"rect": rect,
		"surface": surface,
		"map": 0 if map == null else map.get_instance_id(),
	}


## Drop a volume. Safe to call when it was never registered — every teardown path
## calls this, including ones that run before a volume was ever added.
static func unregister_volume(id: StringName) -> void:
	_volumes.erase(id)


## Everything registered, gone. Only for a full world teardown or a test.
static func clear_volumes() -> void:
	_volumes.clear()


## The surface at [param world_position].
##
## [param floor_layer] is optional: pass the map's ground TileMapLayer to enable
## the tile-data path. Without it only volumes are consulted, which is the
## correct behaviour for every map in this project today.
static func surface_at(
	world_position: Vector2,
	context_map: Node = null,
	floor_layer: TileMapLayer = null
) -> StringName:
	# 1. Volumes override authored ground.
	var context_id: int = 0 if context_map == null else context_map.get_instance_id()
	for id: StringName in _volumes:
		var entry: Dictionary = _volumes[id]
		var scope: int = int(entry.get("map", 0))
		# A scoped volume only answers for its own map. An unscoped one (0)
		# answers everywhere, and so does any query that supplies no context.
		if scope != 0 and context_id != 0 and scope != context_id:
			continue
		if (entry["rect"] as Rect2).has_point(world_position):
			return entry["surface"]

	# 2. The tileset's own declaration, when it has one.
	if floor_layer == null or floor_layer.tile_set == null:
		return DEFAULT
	var cell: Vector2i = floor_layer.local_to_map(
		floor_layer.to_local(world_position)
	)
	var data: TileData = floor_layer.get_cell_tile_data(cell)
	if data == null:
		return DEFAULT
	# has_custom_data would be the obvious guard, but TileData does not expose
	# one — get_custom_data on an undeclared layer returns null, and that is the
	# check. Anything that is not a non-empty StringName is DEFAULT.
	var value: Variant = data.get_custom_data(String(TILE_DATA_KEY))
	if value == null:
		return DEFAULT
	var name: StringName = StringName(str(value))
	return name if not name.is_empty() else DEFAULT


## True when [param surface] should be walked on with slip physics.
static func is_slippery(surface: StringName) -> bool:
	return surface == ICE
