extends MenuShell
## The Vault - Titles, Skins, Cosmetics and Pets, bought with Ark Coins. Opened from
## the Curator; individual Curator buttons jump to a tab via open(arg).
##
## PREMIUM PURCHASING lives here rather than in the three tabs, because all three
## sell the same way and the lockout has to be one state, not three. A tab says
## only "this is selected"; cost, ownership and the buy button are this shell's.
##
## THE BALANCE IS NEVER CACHED ACROSS OPENS. It is fetched on show and replaced by
## whatever the purchase response reports. A number left over from last time is
## worse than no number - it is a number the player will believe.


const TITLES_SCENE: PackedScene = preload("res://source/client/ui/menus/titles/titles_menu.tscn")
const SKINS_SCENE: PackedScene = preload("res://source/client/ui/menus/skins/skins_menu.tscn")
const COSMETICS_SCENE: PackedScene = preload("res://source/client/ui/menus/cosmetics/cosmetics_menu.tscn")
const VaultStyle := preload("res://source/client/ui/menus/vault/vault_style.gd")

## The Ark Coin mark. Generated by tools/build_ark_coin_icon.py - the same file
## the website ships, so the coin on a price tag and the coin in this header
## cannot drift apart.
const COIN_ICON: Texture2D = preload("res://assets/sprites/ui/ark_coin.png")
## A whole divisor of the 64px source, so NEAREST scaling lands on pixel
## boundaries instead of smearing the rim.
const COIN_PX: int = 16

const TAB_TITLES := &"titles"
const TAB_SKINS := &"skins"
const TAB_COSMETICS := &"cosmetics"
## Pets are cosmetics too (the "pet" slot), served by a second copy of the
## cosmetics wardrobe filtered to that one slot - see _embed_cosmetics.
const TAB_PETS := &"pets"

## Failure reasons the server and the web backend can return, in player words.
## Anything not listed falls back to a generic line rather than printing a slug.
const REASON_TEXT: Dictionary = {
	"insufficient_funds": "Not enough Arkenelle currency.",
	"already_owned": "You already own that.",
	"in_flight": "A purchase is already going through.",
	"no_account": "Link a website account to buy from the Vault.",
	"no_player": "You are not in the world right now.",
	"not_configured": "The store is offline right now.",
	"unauthorized": "The store rejected this server. Tell a dev.",
	"unknown_item": "That is not for sale.",
	"duplicate": "That purchase already went through.",
	"rate_limited": "Slow down a moment.",
	"backend_error": "The store had a problem. Nothing was charged.",
	"timeout": "The store did not answer. Check your balance before retrying.",
	"network": "Network error. Nothing was charged.",
	"bad_json": "The store sent something unreadable. Nothing was charged.",
}

var _tab: StringName = TAB_TITLES
var _tab_buttons: Dictionary = {}
var _panels: Dictionary = {}

## item_id -> catalog row {label, cost, owned, ...}. Server-sent; the client never
## computes a price.
var _catalog: Dictionary = {}
var _selected: String = ""
var _balance: int = -1        # -1 = not yet known, distinct from a real zero
var _purchasable: bool = false
var _processing: bool = false

var _balance_label: Label
var _buy_button: Button
var _status_label: Label


func _ready() -> void:
	build_shell("The Vault", null, true)
	# OPAQUE. The fullscreen shell's half-alpha dim let the Guild House - its NPCs
	# and the leaderboard statues' text - read straight through item descriptions
	# and prices. Nothing in a shop may compete with the thing being sold.
	backdrop.color = VaultStyle.BG
	_build_layout()
	_select_tab(TAB_TITLES)
	# Pushes, not responses: the server acks a purchase immediately and settles it
	# later, so the outcome arrives here and not on the request's callback.
	Client.subscribe(&"vault.balance.result", _on_balance)
	Client.subscribe(&"vault.purchase.result", _on_purchased)
	visibility_changed.connect(func() -> void:
		if visible:
			_refresh())
	_refresh.call_deferred()


func _exit_tree() -> void:
	Client.unsubscribe(&"vault.balance.result", _on_balance)
	Client.unsubscribe(&"vault.purchase.result", _on_purchased)


func open(arg: Variant = null) -> void:
	var key: String = str(arg).strip_edges().to_lower()
	match key:
		"skins":
			_select_tab(TAB_SKINS)
		"cosmetics":
			_select_tab(TAB_COSMETICS)
		"pets":
			_select_tab(TAB_PETS)
		_:
			_select_tab(TAB_TITLES)


## Called by a tab when its highlighted entry changes. The token is a VaultGrants
## token built client-side by the tab - it is only ever echoed back to the server,
## which re-resolves it, so a forged one resolves to nothing.
func set_selection(item_id: String) -> void:
	var next: String = item_id.strip_edges()
	# Only on a real change, and never mid-purchase: every failure path sets a
	# message and then calls _update_buy, so clearing on any refresh would erase
	# the reason before anyone could read it.
	if next != _selected and not _processing:
		_say("")
	_selected = next
	_update_buy()


func _build_layout() -> void:
	var col: VBoxContainer = VBoxContainer.new()
	col.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	col.size_flags_vertical = Control.SIZE_EXPAND_FILL
	col.add_theme_constant_override(&"separation", 8)
	content.add_child(col)

	# The coin and the number are ONE unit, the same way they are on the
	# storefront and on a price tag. A bare integer in a header is not a currency:
	# there is nothing to recognise in a shop row, and nothing to put beside a
	# price anywhere else in the game.
	var balance_row: HBoxContainer = HBoxContainer.new()
	balance_row.alignment = BoxContainer.ALIGNMENT_END
	balance_row.add_theme_constant_override(&"separation", 5)
	header_right.add_child(balance_row)

	var coin: TextureRect = TextureRect.new()
	coin.texture = COIN_ICON
	# NEAREST, and sized to a whole multiple of the 64px source. Anything else
	# resamples a pixel-art coin into mush at exactly the size it is smallest.
	coin.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	coin.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	coin.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	coin.custom_minimum_size = Vector2(COIN_PX, COIN_PX)
	coin.tooltip_text = "Ark Coins"
	balance_row.add_child(coin)

	_balance_label = Label.new()
	_balance_label.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	_balance_label.add_theme_font_size_override(&"font_size", 14)
	_balance_label.text = "..."
	balance_row.add_child(_balance_label)

	_build_purchase_bar(balance_row)

	var tabs: HBoxContainer = HBoxContainer.new()
	tabs.alignment = BoxContainer.ALIGNMENT_CENTER
	tabs.add_theme_constant_override(&"separation", 6)
	col.add_child(tabs)
	_add_tab_button(tabs, TAB_TITLES, "Titles")
	_add_tab_button(tabs, TAB_SKINS, "Skins")
	_add_tab_button(tabs, TAB_COSMETICS, "Cosmetics")
	_add_tab_button(tabs, TAB_PETS, "Pets")

	var body: Control = Control.new()
	body.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	body.size_flags_vertical = Control.SIZE_EXPAND_FILL
	col.add_child(body)

	_embed(body, TAB_TITLES, TITLES_SCENE)
	_embed(body, TAB_SKINS, SKINS_SCENE)
	_embed(body, TAB_COSMETICS, COSMETICS_SCENE, {&"exclude_slots": [&"pet"]})
	_embed(body, TAB_PETS, COSMETICS_SCENE, {&"slots": [&"pet"]})

	# NOTHING ELSE GOES IN THIS COLUMN. See _build_purchase_bar - the three
	# embedded panels are full-height layouts and have no vertical budget to give.


## The result line lives in the header beside the balance; the Buy button does
## not - it is mounted into the visible tab by _select_tab.
##
## THEY USED TO BE A FULL-WIDTH BAR AT THE BOTTOM OF THE COLUMN, AND THAT WAS
## BROKEN. The three embedded panels (titles, skins, cosmetics) are each a
## full-height layout that already ends in its own Wear / Equip / Take off
## buttons, sized against the whole 960x540 menu. A status label plus a 44px
## button below them took ~70px the panels did not have, so their own buttons
## overflowed the body Control - which does not clip - and painted straight
## through the Buy bar. Every tab was affected; Skins lost "Wear" off the bottom
## edge entirely.
##
## Putting the purchase controls in the header costs the body ZERO height, which
## is the only arrangement that fixes all three panels without editing all three.
func _build_purchase_bar(row: HBoxContainer) -> void:
	var spacer: Control = Control.new()
	spacer.custom_minimum_size = Vector2(10, 0)
	row.add_child(spacer)

	_status_label = Label.new()
	_status_label.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	_status_label.add_theme_font_size_override(&"font_size", 11)
	_status_label.modulate = Color(1, 1, 1, 0.75)
	# Elided rather than wrapped: the header is one line tall, and a reason that
	# needs more room than this is in the tooltip.
	_status_label.text_overrun_behavior = TextServer.OVERRUN_TRIM_ELLIPSIS
	_status_label.custom_minimum_size = Vector2(210, 0)
	_status_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT
	# Hidden until it has something to say. An HBoxContainer skips invisible
	# children entirely, so an empty status stops reserving 210px and Close sits
	# where it belongs instead of being shoved into the middle of the header.
	_status_label.visible = false
	row.add_child(_status_label)

	# NOT added to the header. It is mounted into whichever tab is showing, just
	# above that tab's own Wear / Equip button - see _select_tab. Full width and
	# 18pt because a price is the number a buyer is actually reading; the 14pt
	# corner version was too small to check before clicking.
	_buy_button = Button.new()
	_buy_button.custom_minimum_size = Vector2(0, 40)
	_buy_button.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	VaultStyle.style_primary(_buy_button)
	_buy_button.disabled = true
	_buy_button.pressed.connect(_on_buy_pressed)


func _add_tab_button(row: HBoxContainer, id: StringName, label: String) -> void:
	var b: Button = Button.new()
	b.text = label
	b.toggle_mode = true
	b.custom_minimum_size = Vector2(0, 36)
	b.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	b.add_theme_font_size_override(&"font_size", 16)
	VaultStyle.style_tab(b)
	b.pressed.connect(_select_tab.bind(id))
	row.add_child(b)
	_tab_buttons[id] = b


## [param meta] is set on the panel BEFORE it enters the tree, so its _ready sees
## it - that is how the two wardrobe copies learn which slots they show.
func _embed(body: Control, id: StringName, scene: PackedScene, meta: Dictionary = {}) -> void:
	var panel: Control = scene.instantiate()
	panel.set_meta(&"embedded", true)
	for key: StringName in meta:
		panel.set_meta(key, meta[key])
	panel.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	panel.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	panel.size_flags_vertical = Control.SIZE_EXPAND_FILL
	body.add_child(panel)
	_panels[id] = panel


func _select_tab(id: StringName) -> void:
	_tab = id
	for key: StringName in _tab_buttons:
		(_tab_buttons[key] as Button).button_pressed = (key == id)
	for key: StringName in _panels:
		var panel: Control = _panels[key]
		panel.visible = (key == id)
	# Ask the newly visible panel what it is showing, rather than blanking the
	# selection and waiting for its own state round trip to come back - that
	# left the button reading "Not for sale" for the length of a request every
	# single time a tab was clicked.
	_selected = ""
	var shown: Control = _panels.get(id)
	if shown != null:
		# Re-home the Buy button into the tab now showing. One button moved
		# rather than three buttons kept in sync, so "Processing..." and the
		# in-flight lock can only ever exist in one place.
		if shown.has_method("mount_purchase_button"):
			shown.call("mount_purchase_button", _buy_button)
		if shown.has_method("announce_selection_now"):
			shown.call("announce_selection_now")
	_update_buy()


func _refresh() -> void:
	if InstanceClient.current == null:
		return
	# Deliberately NOT cleared to 0 - an unknown balance must not read as broke.
	_balance = -1
	_balance_label.text = "..."
	var instance_name: String = String(InstanceClient.current.name)
	Client.request_data(&"vault.catalog", _on_catalog, {}, instance_name)
	Client.request_data(&"vault.balance", _on_balance_ack, {}, instance_name)


func _on_catalog(data: Dictionary) -> void:
	_catalog.clear()
	if not bool(data.get("ok", false)):
		_update_buy()
		return
	_purchasable = bool(data.get("purchasable", false))
	for row: Variant in data.get("items", []):
		var entry: Dictionary = row as Dictionary
		_catalog[str(entry.get("item_id", ""))] = entry
	_update_buy()
	_refresh_shelves()


## One catalog row, for a tab's shelf to price its list. {} when not for sale.
func catalog_entry(item_id: String) -> Dictionary:
	return _catalog.get(item_id.strip_edges(), {}) as Dictionary


## Every tab re-reads its row tags - prices arrived, or something was bought.
func _refresh_shelves() -> void:
	for key: StringName in _panels:
		var panel: Control = _panels[key]
		if panel.has_method("refresh_shelf"):
			panel.call("refresh_shelf")


## The ack only says the fetch started. The number arrives on the push below.
func _on_balance_ack(data: Dictionary) -> void:
	if bool(data.get("ok", false)):
		return
	_balance_label.text = "-"
	_say(_reason_text(str(data.get("reason", ""))))


func _on_balance(data: Dictionary) -> void:
	if not bool(data.get("ok", false)):
		_balance_label.text = "-"
		_say(_reason_text(str(data.get("reason", ""))))
		return
	_balance = int(data.get("balance", 0))
	_balance_label.text = str(_balance)
	_update_buy()


func _on_buy_pressed() -> void:
	if _processing or _selected.is_empty() or InstanceClient.current == null:
		return
	# Locked BEFORE the request goes out, and released only by the settle push or
	# the request's own failure - this is the whole double-click defence on the
	# client side. The server's in-flight guard is the one that actually counts.
	_processing = true
	_say("Processing transaction...")
	_update_buy()
	Client.request_data(
		&"vault.purchase",
		_on_purchase_ack,
		{"item_id": _selected},
		String(InstanceClient.current.name)
	)


## Ack, not outcome. A false here means the purchase never started and nothing was
## charged, so the button can come straight back.
func _on_purchase_ack(data: Dictionary) -> void:
	if bool(data.get("ok", false)):
		return
	_processing = false
	_say(_reason_text(str(data.get("reason", ""))))
	_update_buy()


func _on_purchased(data: Dictionary) -> void:
	_processing = false
	var item_id: String = str(data.get("item_id", ""))
	if not bool(data.get("ok", false)):
		_say(_reason_text(str(data.get("reason", ""))))
		_update_buy()
		return
	if _catalog.has(item_id):
		(_catalog[item_id] as Dictionary)["owned"] = true
	if data.has("balance"):
		_balance = int(data.get("balance", 0))
		_balance_label.text = str(_balance)
	_say("Unlocked %s." % str(data.get("label", "item")))
	_update_buy()
	_refresh_shelves()
	# The tabs only learn what the player owns from their own state fetch, so
	# without this a fresh purchase left Equip greyed out until the Vault was
	# closed and reopened.
	for key: StringName in _panels:
		var panel: Control = _panels[key]
		if panel.has_method("refresh_after_purchase"):
			panel.call("refresh_after_purchase")


## Buy only exists when there is something to buy. A greyed "Owned" or "Not for
## sale" bar stacked over Equip / Take off was a third button saying what the
## shelf row already says.
func _update_buy() -> void:
	if _processing:
		_buy_button.visible = true
		_buy_button.text = "Processing..."
		_buy_button.disabled = true
		return
	var entry: Dictionary = _catalog.get(_selected, {}) as Dictionary
	if entry.is_empty() or bool(entry.get("owned", false)):
		_buy_button.visible = false
		return
	# The tab's own ownership too, the same source its shelf row reads - so a row
	# saying Owned can never sit over a Buy button offering the same item.
	var shown: Control = _panels.get(_tab)
	if shown != null and shown.has_method("selection_owned") and bool(shown.call("selection_owned")):
		_buy_button.visible = false
		return
	_buy_button.visible = true
	var cost: int = int(entry.get("cost", 0))
	_buy_button.text = "Buy for %d Ark Coins" % cost
	# Unknown balance (-1) still allows the click: the server is the authority on
	# affordability, and greying the button out on a failed fetch would look like
	# the item is unavailable.
	_buy_button.disabled = not _purchasable or (_balance >= 0 and _balance < cost)


func _reason_text(reason: String) -> String:
	return str(REASON_TEXT.get(reason, "Something went wrong. Nothing was charged."))


## The status line is elided in the header, so the full text lives in the
## tooltip. One setter for both, or the two drift apart.
func _say(message: String) -> void:
	if _status_label == null:
		return
	_status_label.text = message
	_status_label.tooltip_text = message
	_status_label.visible = not message.is_empty()
