class_name PaperDollData
## GENERATED by tools/paperdoll/import_manaseed.py - do not edit by hand.
##
## Describes the Mana Seed sheet layout and the rosters actually present in
## assets/sprites/characters/manaseed/. Re-run the importer after adding a pack.

const FRAME_SIZE: int = 64
const SHEET_SIZE: int = 512
const GRID_COLS: int = 8
const GRID_ROWS: int = 8

## Row order on every page, verified against the art rather than assumed.
enum Facing { DOWN = 0, UP = 1, RIGHT = 2, LEFT = 3 }

## Rows 0-3 hold the standing/push/pull/jump poses; rows 4-7 hold walk+run.
const STAND_ROW_BASE: int = 0
const WALK_ROW_BASE: int = 4

## Standing is a single cell; walk is the first six columns.
const STAND_COL: int = 0
const WALK_COLS: Array[int] = [0, 1, 2, 3, 4, 5]
## Run reuses walk frames but swaps in the two dedicated run frames (cols 6,7)
## for the 3rd and 6th - straight from the pack's own guide.
const RUN_COLS: Array[int] = [0, 1, 6, 3, 4, 7]

## Per-frame hold in seconds, from the pack's timing guide. Run is deliberately
## uneven (80/55/125) - even timing makes the borrowed frames read wrong.
const WALK_FRAME_TIME: float = 0.135
const RUN_FRAME_TIMES: Array[float] = [0.08, 0.055, 0.125, 0.08, 0.055, 0.125]

## Paper-doll draw order, straight from the pack's naming convention.
const LAYER_ORDER: Array[StringName] = [&"0bot", &"1out", &"2clo", &"3fac", &"4har", &"5hat", &"6tla", &"7tlb"]

## Creator rosters - only entries with art on disk.
const BODY_VARIANTS: Array[StringName] = [&"00", &"01", &"02", &"03", &"04", &"05", &"06", &"07", &"08", &"09", &"10"]
const HAIR_STYLES: Array[StringName] = [&"bob1", &"bob2", &"dap1", &"flat", &"fro1", &"pon1", &"spk2"]
const HAIR_COLORS: Array[StringName] = [&"00", &"01", &"02", &"03", &"04", &"05", &"06", &"07", &"08", &"09", &"10", &"11", &"12", &"13"]
const OUTFITS: Array[StringName] = [&"alch", &"angl", &"bksm", &"boxr", &"fstr", &"pfdr", &"pfpn", &"undi"]
const HATS: Array[StringName] = [&"band", &"hddn", &"hdpl", &"pfbn", &"pfht", &"pnty", &"rnht"]
const CLOAKS: Array[StringName] = [&"lnpl", &"mnpl"]

## Display names for the four-letter pack codes.
const ITEM_NAMES: Dictionary = {
	&"alch": "Alchemist",
	&"angl": "Angler",
	&"band": "Bandana",
	&"bksm": "Blacksmith",
	&"bob1": "Bob",
	&"bob2": "Long Bob",
	&"boxr": "Boxers",
	&"dap1": "Dapper",
	&"flat": "Flat",
	&"fro1": "Afro",
	&"fstr": "Forester",
	&"hddn": "Hood",
	&"hdpl": "Hood (Up)",
	&"lnpl": "Long Cloak",
	&"mnpl": "Mantle",
	&"pfbn": "Bonnet",
	&"pfdr": "Farm Dress",
	&"pfht": "Straw Hat",
	&"pfpn": "Farmhand",
	&"pnty": "Pointed Hat",
	&"pon1": "Ponytail",
	&"rnht": "Rain Hat",
	&"spk2": "Spiked",
	&"undi": "Undershirt",
}

## Per-item variant counts, so the creator never offers a colour that is
## missing for one style (hair variants differ: pon1 ships 13, the rest 14).
const VARIANTS: Dictionary = {
	&"0bot/lnpl": [&"01", &"02", &"03", &"04", &"05", &"06", &"07", &"08", &"09", &"10"],
	&"1out/alch": [&"01", &"02", &"03", &"04", &"05"],
	&"1out/angl": [&"01", &"02", &"03", &"04", &"05"],
	&"1out/bksm": [&"01", &"02", &"03", &"04", &"05"],
	&"1out/boxr": [&"01"],
	&"1out/fstr": [&"01", &"02", &"03", &"04", &"05"],
	&"1out/pfdr": [&"01", &"02", &"03", &"04", &"05"],
	&"1out/pfpn": [&"01", &"02", &"03", &"04", &"05"],
	&"1out/undi": [&"01"],
	&"2clo/lnpl": [&"01", &"02", &"03", &"04", &"05", &"06", &"07", &"08", &"09", &"10"],
	&"2clo/mnpl": [&"01", &"02", &"03", &"04", &"05", &"06", &"07", &"08", &"09", &"10"],
	&"3fac/gogl": [&"01", &"02", &"03", &"04", &"05"],
	&"4har/bob1": [&"00", &"01", &"02", &"03", &"04", &"05", &"06", &"07", &"08", &"09", &"10", &"11", &"12", &"13"],
	&"4har/bob2": [&"00", &"01", &"02", &"03", &"04", &"05", &"06", &"07", &"08", &"09", &"10", &"11", &"12", &"13"],
	&"4har/dap1": [&"00", &"01", &"02", &"03", &"04", &"05", &"06", &"07", &"08", &"09", &"10", &"11", &"12", &"13"],
	&"4har/flat": [&"00", &"01", &"02", &"03", &"04", &"05", &"06", &"07", &"08", &"09", &"10", &"11", &"12", &"13"],
	&"4har/fro1": [&"00", &"01", &"02", &"03", &"04", &"05", &"06", &"07", &"08", &"09", &"10", &"11", &"12", &"13"],
	&"4har/pon1": [&"00", &"01", &"02", &"03", &"04", &"05", &"06", &"07", &"08", &"09", &"10", &"12", &"13"],
	&"4har/spk2": [&"00", &"01", &"02", &"03", &"04", &"05", &"06", &"07", &"08", &"09", &"10", &"11", &"12", &"13"],
	&"5hat/band": [&"01", &"02", &"03", &"04", &"05"],
	&"5hat/hddn": [&"01", &"02", &"03", &"04", &"05", &"06", &"07", &"08", &"09", &"10"],
	&"5hat/hdpl": [&"01", &"02", &"03", &"04", &"05", &"06", &"07", &"08", &"09", &"10"],
	&"5hat/pfbn": [&"01", &"02", &"03", &"04", &"05"],
	&"5hat/pfht": [&"01", &"02", &"03", &"04", &"05"],
	&"5hat/pnty": [&"01", &"02", &"03", &"04", &"05"],
	&"5hat/rnht": [&"01", &"02", &"03", &"04", &"05"],
	&"6tla/ax01": [&"01", &"02", &"03", &"04", &"05"],
	&"6tla/mc01": [&"01", &"02", &"03", &"04", &"05"],
	&"6tla/sw01": [&"01", &"02", &"03", &"04", &"05"],
	&"7tlb/sh01": [&"01", &"02", &"03", &"04", &"05"],
	&"7tlb/sh02": [&"01", &"02", &"03", &"04", &"05"],
	&"7tlb/sh03": [&"01", &"02", &"03", &"04", &"05"],
}
