"""Draw the Dragon / Obsidian / Celestial / Astralite tool heads.

LEGIBILITY FIRST, MATERIAL SECOND.

The first attempt at these gave every tier its own head geometry — horns, a
cleaved wedge, a haloed crescent, a pronged fork. Each tier was unmistakable and
the tool TYPE was not: at 16x32 in a bag grid you could not tell a pickaxe from
an axe, which is the only thing the silhouette actually has to communicate. That
was rejected, correctly.

So the silhouette is now fixed per TOOL TYPE and shared across all four tiers,
matching the Bronze->Runite shapes players already read:

    Pickaxe  full-width arched head, two points angled down, centred haft
    Sickle   blade sweeping up-left, over, and down to a point at the right,
             plus the L-shaped side grip on the haft
    Axe      straight poll flush with the haft, weighted blade bulging out to
             one side with a convex cutting edge

Tier identity is carried ONLY by:
  * the metal ramp (unchanged from the rest of the tier art)
  * a 2-3 pixel ornament inset INSIDE the head, never breaking its outline
  * two accent bands on the haft

Masks are authored as explicit pixel grids rather than generated from arcs and
polygons. At this size every pixel is a design decision, and the parametric
version is what produced the amorphous blobs.

Output is a 192x112 sheet per tier laid out on the SAME grid as the base weapon
sheets, so the tool items keep the canonical regions:
    pickaxe Rect2(0, 48, 16, 32)
    sickle  Rect2(32, 48, 16, 32)
    axe     Rect2(112, 48, 16, 32)

    python tools/build_high_tier_tool_art.py
"""
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "assets", "sprites", "items", "weapons", "tools", "high_tier")

CELL_W, CELL_H = 16, 32
SHEET_W, SHEET_H = 192, 112
# canonical cell origins on the base weapon sheets — do not move these
SLOTS = {"pickaxe": (0, 48), "sickle": (32, 48), "axe": (112, 48)}

# Same ramps as the rest of the tier art, so a Dragon pick reads as the same
# metal as Dragon plate. dark -> light, sampled by depth.
RAMPS = {
    "dragon":    [(28, 6, 6), (96, 16, 12), (168, 34, 24), (226, 76, 44), (255, 186, 140)],
    "obsidian":  [(26, 4, 42), (70, 12, 96), (128, 30, 152), (186, 82, 236), (238, 196, 255)],
    "celestial": [(24, 24, 42), (70, 76, 104), (186, 170, 104), (226, 208, 120), (242, 234, 196)],
    "astralite": [(26, 22, 46), (78, 60, 132), (150, 110, 210), (216, 170, 246), (250, 240, 255)],
}
OUTLINE = {
    "dragon": (18, 4, 4), "obsidian": (14, 2, 24),
    "celestial": (16, 16, 30), "astralite": (16, 12, 32),
}
# The ornament colour — deliberately the brightest step of the tier ramp, so it
# reads as the metal catching light and never as a second material.
ACCENT = {t: r[-1] for t, r in RAMPS.items()}
HAFT = [(38, 24, 14), (74, 48, 26), (110, 74, 40), (146, 104, 60)]

# --- silhouettes ------------------------------------------------------------
# '.' empty   'M' metal   'W' wood haft
# Shared by every tier. Change one of these and you change all four tools.

PICKAXE = """
................
.......MM.......
.......MM.......
....MMMMMMMM....
..MMMMMMMMMMMM..
.MMMM.MMMM.MMMM.
MMM...MMMM...MMM
MM....MMMM....MM
M.....MMMM.....M
......MMMM......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
................
"""

SICKLE = """
................
..MM............
..MMM...........
..MMMMMM........
..MMMMMMMMM.....
..MMMMMMMMMMM...
...MMMMMMMMMMM..
....MMM....MMMM.
.......MM...MMMM
.......MM...MMMM
.......WW...MMM.
.......WW..MMM..
.......WW.MMM...
.......WW.MM....
.......WW.M.....
.......WW.......
.......WW.......
.......WWMMM....
.......WW..M....
.......WW..M....
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
................
"""

AXE = """
................
................
.......WW.......
......MWWMMM....
......MWWMMMMM..
......MWWMMMMMM.
......MWWMMMMMM.
......MWWMMMMMMM
......MWWMMMMMMM
......MWWMMMMMMM
......MWWMMMMMM.
......MWWMMMMMM.
......MWWMMMMM..
......MWWMMM....
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
................
"""

# The Dragon rod keeps the shipped rod family's silhouette — a 2px blank, a hook
# at the tip, line beads trailing off it and a reel block low on the shaft. The
# earlier redesign broke that family for no gain.
ROD = """
................
.......MM.......
.......MM.......
.......MM.......
......MM........
......MM........
......MM........
......MM........
......MM........
......MM........
......WW........
......WW........
......WW........
......WW........
...MMMMMMM......
...MMMMMMM......
...MMMMMMM......
...MMMMMMM......
...MMMMMMM......
......WW........
......WW........
......WW........
......WW........
......WW........
......WW........
......WW........
......WW........
......WW........
......WW........
......WW........
......WW........
................
"""

MASKS = {"pickaxe": PICKAXE, "sickle": SICKLE, "axe": AXE}

# Ornament: a tiny motif inset in the head. Offsets are relative to an anchor
# that sits well inside the silhouette, so no ornament can nibble the outline.
ANCHOR = {"pickaxe": (8, 4), "sickle": (4, 4), "axe": (11, 8)}
MOTIF = {
    "dragon":    [(0, 0), (0, 1)],           # an ember slit
    "obsidian":  [(0, 0), (1, 1)],           # a chipped facet
    "celestial": [(0, 0), (-1, 1), (1, 1)],  # a small radiance
    "astralite": [(0, 0), (2, 1), (-2, 1)],  # a spread constellation
}
# Two accent bands on the haft, the same rows on every tool, so a tier is
# identifiable even when the head is off-screen behind the player sprite.
HAFT_BANDS = (24, 27)


def _lerp(a, b, t):
    return tuple(round(a[i] + (b[i] - a[i]) * t) for i in range(3))


def _ramp(colors, t):
    t = max(0.0, min(1.0, t))
    pos = t * (len(colors) - 1)
    i = min(int(pos), len(colors) - 2)
    return _lerp(colors[i], colors[i + 1], pos - i)


def parse(art):
    """ASCII grid -> {char: set of (x, y)}. Validates the grid is exactly 16x32."""
    rows = [r for r in art.split("\n") if r != ""]
    if len(rows) != CELL_H:
        raise SystemExit(f"mask must be {CELL_H} rows, got {len(rows)}")
    out = {}
    for y, row in enumerate(rows):
        if len(row) != CELL_W:
            raise SystemExit(f"row {y} must be {CELL_W} wide, got {len(row)}")
        for x, ch in enumerate(row):
            if ch != ".":
                out.setdefault(ch, set()).add((x, y))
    return out


def shade(cells, ramp, outline, metal=True):
    """Shade a pixel set: depth from distance to the silhouette edge plus a key
    light from the upper-left, then a 1px keyline around it."""
    im = Image.new("RGBA", (CELL_W, CELL_H), (0, 0, 0, 0))
    if not cells:
        return im
    px = im.load()

    for (x, y) in cells:
        # how deep this pixel sits inside the shape, capped at 3
        d = 1
        while d < 4:
            ring = [(x + dx, y + dy)
                    for dx in range(-d, d + 1) for dy in range(-d, d + 1)
                    if max(abs(dx), abs(dy)) == d]
            if any(q not in cells for q in ring):
                break
            d += 1
        depth = min(1.0, (d - 1) / 2.0)
        lit = ((x - 1, y) not in cells) or ((x, y - 1) not in cells)
        dark = ((x + 1, y) not in cells) or ((x, y + 1) not in cells)
        t = 0.34 + depth * 0.30
        if d == 1 and lit:
            t += 0.30 if metal else 0.20
        elif d == 1 and dark:
            t -= 0.22 if metal else 0.14
        px[x, y] = _ramp(ramp, t) + (255,)

    for (x, y) in cells:
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < CELL_W and 0 <= ny < CELL_H and (nx, ny) not in cells:
                if px[nx, ny][3] == 0:
                    px[nx, ny] = outline + (255,)
    return im


def _compose(tier, layers):
    metal = layers.get("M", set())
    wood = layers.get("W", set())
    im = Image.new("RGBA", (CELL_W, CELL_H), (0, 0, 0, 0))
    im.alpha_composite(shade(wood, HAFT, OUTLINE[tier], metal=False))
    im.alpha_composite(shade(metal, RAMPS[tier], OUTLINE[tier]))
    return im, metal, wood


def build_tool(tier, tool):
    im, metal, wood = _compose(tier, parse(MASKS[tool]))
    px = im.load()
    ax, ay = ANCHOR[tool]
    for dx, dy in MOTIF[tier]:
        p = (ax + dx, ay + dy)
        if p in metal:                       # never paint outside the head
            px[p] = ACCENT[tier] + (255,)
    for by in HAFT_BANDS:
        for x in range(CELL_W):
            if (x, by) in wood:
                px[x, by] = _lerp(ACCENT[tier], HAFT[-1], 0.35) + (255,)
    return im


def build_rod(tier="dragon"):
    im, metal, _wood = _compose(tier, parse(ROD))
    px = im.load()
    for p in ((8, 1), (9, 2)):               # hook at the tip
        px[p] = ACCENT[tier] + (255,)
    for p in ((10, 3), (11, 5), (11, 7)):    # line beads trailing off it
        px[p] = _lerp(ACCENT[tier], (255, 255, 255), 0.25) + (255,)
    return im


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    for tier in RAMPS:
        sheet = Image.new("RGBA", (SHEET_W, SHEET_H), (0, 0, 0, 0))
        for tool, (sx, sy) in SLOTS.items():
            sheet.alpha_composite(build_tool(tier, tool), (sx, sy))
        path = os.path.join(OUT_DIR, f"tools_{tier}.png")
        sheet.save(path)
        print("wrote", os.path.relpath(path, ROOT))
    path = os.path.join(OUT_DIR, "fishing_rod_dragon.png")
    build_rod().save(path)
    print("wrote", os.path.relpath(path, ROOT))


if __name__ == "__main__":
    main()
